endpoints:
    beans:
        enabled: true
        sensitive: false
        id: beans
    info:
        enabled: true
        sensitive: false
        id: info
    health:
        enabled: true
        sensitive: false
        details-visible: ANONYMOUS
        id: health
    routes:
        enabled: true
        sensitive: false
        id: routes